export const INCREMENT_GAME_COUNT = "INCREMENT_GAME_COUNT";
export const SET_SELECTED_RESOURCE = "SET_SELECTED_RESOURCE";
export const INCREMENT_WIN_COUNT_BY_PLAYER_ID =
  "INCREMENT_WIN_COUNT_BY_PLAYER_ID";
