export const SET_GAME_COUNT = "SET_GAME_COUNT";
export const SET_RESOURCE = "SET_RESOURCE";
export const INCREMENT_WIN_COUNT_BY_PLAYER_ID =
  "INCREMENT_WIN_COUNT_BY_PLAYER_ID";
export const SET_TOP_TRUMP_BY_PLAYER_ID = "SET_TOP_TRUMP_BY_PLAYER_ID";
export const SET_ATTRIBUTE = "SET_ATTRIBUTE";
